**Fixed:**

* Fixed exception being thrown by PyPy due to https://github.com/wlav/cppyy/issues/209.
